name: action_process_text
description: A flutter plugin for ACTION_PROCESS_TEXT implementation in android.
version: 0.0.3
repository: https://github.com/coder-with-a-bushido/ACTION_PROCESS_TEXT-Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.action_process_text
        pluginClass: ActionProcessTextPlugin
      